# Q1

Write a Pandas program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

In [1]:
import pandas as pd

#using "Series" method
asd = [1, 2, 3, 4, 5]
ds = pd.Series(asd)


In [2]:
ds
print(type(ds))

<class 'pandas.core.series.Series'>


# Q2

Write a Pandas program to convert a Panda module Series to Python list and it's type

In [3]:
ds = pd.Series([2, 4, 6, 8, 10])

ds

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [4]:
#converting panda series to List tpe 
ds.tolist()

[2, 4, 6, 8, 10]

# Q3

Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [5]:
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])

In [6]:
#add two panda Series
ds = ds1 + ds2
ds

0     3
1     7
2    11
3    15
4    19
dtype: int64

In [7]:
#subtract two panda Series
ds = ds1- ds2
ds

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [8]:
#multiple two panda Series
ds = ds1 * ds2
ds

0     2
1    12
2    30
3    56
4    90
dtype: int64

In [9]:
#Divide two panda Series
ds = ds1 / ds2
ds

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

# Q4

Write a Pandas program to compare the elements of the two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [10]:
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])

In [11]:
# Equality comparison
ds = ds1 == ds2
ds

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [12]:
# Greater than comparison
ds = ds1 > ds2
ds

0     True
1     True
2     True
3     True
4    False
dtype: bool

In [13]:
# Less than comparison
ds = ds1 < ds2
ds

0    False
1    False
2    False
3    False
4    False
dtype: bool

# Q5

Write a Pandas program to convert a dictionary to a Pandas series.
Sample Series: 
Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64 

In [14]:
Original_dictionary = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
# Converting Python Dict to Panda Series method
pd.Series(Original_dictionary)

a    100
b    200
c    300
d    400
e    800
dtype: int64

In [15]:
Original_dictionary = {'a': [100,200], 'b': [200,400], 'c': [300,600], 'd': [400,900], 'e': [800,600]}
# Converting Python Dict to Panda Series method
pd.Series(Original_dictionary)

a    [100, 200]
b    [200, 400]
c    [300, 600]
d    [400, 900]
e    [800, 600]
dtype: object

# Q6

Write a Pandas program to convert a NumPy array to a Pandas series.
Sample Series: 
  NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50

In [16]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
#Converting Numpy Array to Pandas Series.
series = pd.Series(arr)
series

0    10
1    20
2    30
3    40
4    50
dtype: int32

# Q7

Write a Pandas program to change the data type of given a column or a Series.

    Sample Series: 
    Original Data Series:
    0       100
    1       200
    2    python
    3    300.12
    4       400
    dtype: object

    Change the said data type to numeric:
    0    100.00
    1    200.00
    2       NaN
    3    300.12
    4    400.00
    dtype: float64

In [17]:
# Create the original Series
data_series = pd.Series([100, 200, 'python', 300.12, 400])

# Change the data type to numeric
data_series_numeric = pd.to_numeric(data_series, errors='coerce')

data_series_numeric

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

# Q8

Write a Pandas program to convert the first column of a DataFrame as a Series.

    Sample Output:  
    Original DataFrame
       col1  col2  col3
    0     1     4     7
    1     2     5     5
    2     3     6     8
    3     4     9    12
    4     7     5     1
    5    11     0    11

    1st column as a Series:
    0     1
    1     2
    2     3
    3     4
    4     7
    5    11
    Name: col1, dtype: int64
    <class 'pandas.core.series.Series'>

In [18]:
# Create the original DataFrame
data = {'col1': [1,2,3,4,7,11],
        'col2': [4,5,6,9,5,0],
        'col3': [7,5,8,12,1,11]}
#Convert to pandas Dataframe
df = pd.DataFrame(data)
df

col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

In [19]:
df['col1']

0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64

# Q9

Write a Pandas program to convert a given Series to an array.

    Sample Output: 
    Original Data Series:
    0       100
    1       200
    2    python
    3    300.12
    4       400
    dtype: object
    Series to an array
    ['100' '200' 'python' '300.12' '400']
    <class 'numpy.ndarray'>

In [20]:
# Create a sample Series
od_series = pd.Series([100,200,'python',300.12,400]) 

In [21]:
#Checking type and data of created Series
od_series
type(od_series)

pandas.core.series.Series

In [22]:
# Convert the Series to an array
array = od_series.values
print (type(array))
print (array)

<class 'numpy.ndarray'>
[100 200 'python' 300.12 400]


# Q10

Write a Pandas program to convert Series of lists to one Series.

    Sample Output: 
    Original Series of list
    0    [Red, Green, White]
    1           [Red, Black]
    2               [Yellow]
    dtype: object
    One Series
    0       Red
    1     Green
    2     White
    3       Red
    4     Black
    5    Yellow
    dtype: object

In [23]:
#Creating Python pandas series
series = pd.Series ([['Red', 'Green', 'White'],['Red', 'Black'],['Yellow']])
# Convert the Series of lists to a single Series
one_series = series.explode()#.reset_index(drop=True)
one_series

0       Red
0     Green
0     White
1       Red
1     Black
2    Yellow
dtype: object

In [24]:
#Resetting index to get result as per expetation.
one_series.reset_index(drop=True)

0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

# Q11

Write a Pandas program to sort a given Series.

    Sample Output:
    Original Data Series:
    0       100
    1       200
    2    python
    3    300.12
    4       400
    dtype: object
    0       100
    1       200
    3    300.12
    4       400
    2    python
    dtype: object

In [25]:
series = pd.Series(['100', '200', 'python', '300.12', '400'])
print(series)
#using .sort_value()method to sort values.
new_series = series.sort_values()
print (new_series)

0       100
1       200
2    python
3    300.12
4       400
dtype: object
0       100
1       200
3    300.12
4       400
2    python
dtype: object


# Q12

Write a Pandas program to create a subset of a given series based on value and condition.

    Sample Output:
    Original Data Series:
    0      0
    1      1
    2      2

    ....

    9      9
    10    10
    dtype: int64

    Subset of the above Data Series:
    0    0
    1    1
    2    2
    3    3
    4    4
    5    5
    dtype: int64

In [26]:
import pandas as pd

# Create the original Series
original_series = pd.Series(range(11))

print("Original Data Series:")
print(original_series)

# Create a subset based on a condition
subset = original_series[original_series < 5]

print("Subset Data Series:")
print(subset)


Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64
Subset Data Series:
0    0
1    1
2    2
3    3
4    4
dtype: int64


# Q13

Write a Pandas program to change the order of index of a given series.

    Sample Output:
    Original Data Series:
    A    1
    B    2
    C    3
    D    4
    E    5
    dtype: int64
    Data Series after changing the order of index:
    B    2
    A    1
    C    3
    D    4
    E    5
    dtype: int64

In [27]:
#Creating data series for requirment
series = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print(series)

#Changing Index with reindex method
series = series.reindex(index = ['B','A','C','D','E'])
print(series)


A    1
B    2
C    3
D    4
E    5
dtype: int64
B    2
A    1
C    3
D    4
E    5
dtype: int64


# 15. Write a Pandas program to create the mean and standard deviation of the data of a given Series.

    Sample Output:
    Original Data Series:
    A    1
    B    2
    C    3
    D    4
    E    5
    dtype: int64
    Data Series after changing the order of index:
    B    2
    A    1
    C    3
    D    4
    E    5
    dtype: int64

In [28]:
series = pd.Series([1,2,3,4,5,6,7,8,9,5,3])
print (series.mean(),"mean")
print (series.std(), "Standartd Deviation")

4.818181818181818 mean
2.522624895547565 Standartd Deviation


# 16 Write a Pandas program to get the items of a given series not present in another given series.

    Sample Output:  
    Original Series:
    sr1:
    0    1
    1    2
    2    3
    3    4
    4    5
    dtype: int64
    sr2:
    0     2
    1     4
    2     6
    3     8
    4    10
    dtype: int64

    Items of sr1 not present in sr2:
    0    1
    2    3
    4    5
    dtype: int64

In [29]:
series1 = pd.Series([1,2,3,4,5])
series2 = pd.Series([2,4,6,8,10])
#Check true or false with the help with
print ([~series1.isin(series2)])
result = series1[~series1.isin(series2)]
print (result)

[0     True
1    False
2     True
3    False
4     True
dtype: bool]
0    1
2    3
4    5
dtype: int64


# Q16 Write a Pandas program to get the items which are not common of two given series.

    Sample Output: 
    Original Series:
    sr1: 
    0    1 
    1    2 
    2    3 
    3    4 
    4    5
    dtype: int64
    sr2:
    0     2
    1     4 
    2     6 
    3     8
    4    10 
    dtype: int64 

    Items of a given series not present in another given series: 
    0     1 
    2     3 
    4     5 
    5     6 
    6     8
    7    10 
    dtype: int64

In [30]:
series1 = pd.Series([1,2,3,4,5])
series2 = pd.Series([2,4,6,8,10])

series11 = np.union1d(series1, series2)
series12 = np.intersect1d(series1, series2)
print (series11)
print (series12)

#Converting to Numpy array to pandas series we can also write above code as 
#"series11 = pd.Series(np.union1d(series1, series2))" to avoid converting this here.
a = pd.Series(series11)
b = pd.Series(series12)

result = a[~a.isin(b)]
print (result)

[ 1  2  3  4  5  6  8 10]
[2 4]
0     1
2     3
4     5
5     6
6     8
7    10
dtype: int64


# 17. Write a Pandas program to get the items which are not common of two given series.

    Sample Output:
    Original Series:
    0      3.000938
    1     11.370722
    2     14.612143

    ....

    17    14.118931
    18     8.247458
    19     5.526727
    dtype: float64

    Minimum, 25th percentile, median, 75th, and maximum of a given series:
    [ 3.00093811  8.09463867 10.23353705 12.21537733 14.61214321]

In [31]:
# Create a random number generator with a fixed seed
num = np.random.RandomState(100)

# Generate a Series of 20 numbers sampled from a normal distribution
num_series = pd.Series(num.normal(10,4,20))
print (num_series)
result = np.percentile(num_series,q =[0,25,50,75,100])
print (result)

0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64
[ 3.00093811  8.09463867 10.23353705 12.21537733 14.61214321]


# 18 Write a Pandas program to calculate the frequency counts of each unique value of a given series.

    Sample Output:
    Original Series:
    0     1
    1     7
    2     1
    3     6

    ...


    37    0
    38    4
    39    8
    dtype: object
    Frequency of each unique value of the said series.
    0    9
    2    7
    9    6
    ....
    3    2
    4    1
    5    1
    dtype: int64

In [32]:
num_series = pd.Series(np.take(list('0123456789'), np.random.randint(10, size=40)))
print (num_series)
result = num_series.value_counts()
result

0     1
1     2
2     0
3     0
4     0
5     5
6     8
7     1
8     0
9     1
10    3
11    1
12    5
13    0
14    5
15    8
16    3
17    3
18    2
19    9
20    1
21    3
22    2
23    2
24    0
25    2
26    4
27    8
28    9
29    8
30    4
31    1
32    0
33    4
34    3
35    4
36    1
37    1
38    4
39    7
dtype: object


1    8
0    7
2    5
3    5
4    5
8    4
5    3
9    2
7    1
Name: count, dtype: int64

# Q Write a Pandas program convert the first and last character of each word to upper case in each word of a given series.

    Sample Output:
    Original Series:
    0       php
    1    python
    2      java
    3        c#
    dtype: object

    First and last character of each word to upper case:
    0       PhP
    1    PythoN
    2      JavA
    3        C#
    dtype: object

In [33]:
series = pd.Series(['php', 'python', 'java', 'c#'])
result = series.map(lambda x:x[0].upper()+x[1:-1]+x[-1].upper())
result

0       PhP
1    PythoN
2      JavA
3        C#
dtype: object

# Q: Write a Pandas program to calculate the number of characters in each word in a given series

    Sample Output: 
    Original Series:
    0       Php
    1    Python
    2      Java
    3        C#
    dtype: object

    Number of characters in each word in the said series:
    0    3
    1    6
    2    4
    3    2
    dtype: int64

In [34]:
series = pd.Series(['php', 'python', 'java', 'c#'])
result = series.map(lambda x: len(x))
result

0    3
1    6
2    4
3    2
dtype: int64